function [ output_args ] = ClosedContourDetection3( imageName, contourFile1, contourFile2, mValue, lambda )
%ClosedContourDetection3 A program to find contours in an image
%   Detailed explanation goes here

% 'resources/images/Girl-with-Book-Grayscale.jpg', 9, 10
 

%% Reading the image

imageObject = Image();

imageObject.getImage(imageName, false);


%% make search space by imaginary countour lines

searchObject = SearchSpace();
searchObject.makeSearchSpace(contourFile1,contourFile2, imageObject.imageMatrix, mValue);



%% Display the image

figure(1)
imagesc(imageObject.imageMatrix)
colormap(gray)
%axis square
scaleGraph1 = axis;

%% Load the contour and display it

%contourMatrix = load('init1.ctr');
% plot  contour
hold on;
%this ensures Matlab plots the contour on the same figure

plot(searchObject.contourLine1(:,1),searchObject.contourLine1(:,2),'r+-','LineWidth',2);
plot(searchObject.contourLine2(:,1),searchObject.contourLine2(:,2),'r+-','LineWidth',2);

%% calculate image functional

searchObject.calculateImageFunctional();


%% Construct position matrix and energy function and backtrack
energyObject = EnergyCalculation();
energyObject.findMinimalContour3(searchObject, lambda);

%% plot extra lines
% plot first two lines generated by bresenham's algo
[linesCount, columns] = size(searchObject.lineMatrix);
%for lineIndex = 1 : linesCount
 %   plot(searchObject.lineMatrix(lineIndex, :,1),searchObject.lineMatrix(lineIndex, :,2),'b','LineWidth',1);
%end
% plot real contour matrix
plot(energyObject.realContourMatrix(:,1),energyObject.realContourMatrix(:,2),'g+-','LineWidth',2);
%% Display the contour

figure(2)
imagesc(searchObject.searchSpace)
colormap(gray)
axis square
%axis(scaleGraph1);

hold on;
plot(energyObject.contourMatrix(:,1),energyObject.contourMatrix(:,2),'r+-','LineWidth',2);

%% now extract midpoint
midpointIndex = floor((linesCount + 1)/2);

% shift contours from midpoint
searchObject.shiftMatrices(midpointIndex);

% fix vo, v1
row1 = energyObject.contourMatrix(midpointIndex,1);
row2 = energyObject.contourMatrix(midpointIndex + 1,1);
searchObject.fixFirstTwoPoints(row1, row2);

%% now after making transformation do whole process again

energyObject.findMinimalContour3(searchObject, lambda);

%% Display the contour

figure(3)
imagesc(searchObject.searchSpace)
colormap(gray)
axis square
%axis(scaleGraph1);

hold on;
plot(energyObject.contourMatrix(:,1),energyObject.contourMatrix(:,2),'r+-','LineWidth',2);

figure(1)
hold on;
% plot real contour matrix
plot(energyObject.realContourMatrix(:,1),energyObject.realContourMatrix(:,2),'y','LineWidth',1);




end

